name: Build and Deploy to Scratch Org

# Deploy the code when changes are pushed to the master branch
on:
    push:
        branches:
            - master

jobs:
    deploy:
        name: Deploy to Salesforce
        runs-on: ubuntu-latest

        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2.4.0
              with:
                  node-version: '10.x'

            - name: Decrypt server Key
              run: openssl enc -aes-256-cbc -md sha256 -salt -d -in assets/certificates/server.key.enc -out assets/certificates/server.key -k ${{ secrets.SERVER_KEY_PASSWORD }} -pbkdf2

            - name: Setup SFDX environment variables
              run: |
                  export SALESFORCE_CLI_URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
                  export SFDX_AUTOUPDATE_DISABLE=false
                  export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
                  export SFDX_DOMAIN_RETRY=600
                  export SFDX_LOG_LEVEL=DEBUG

            - name: Install Salesforce CLI
              run: |
                  npm install sfdx-cli
                  node_modules/sfdx-cli/bin/run --version
                  node_modules/sfdx-cli/bin/run plugins --core

            - name: Authenticate to the Dev Hub
              run: node_modules/sfdx-cli/bin/run force:auth:jwt:grant --setdefaultdevhubusername --clientid ${{ secrets.SF_CONSUMER_KEY }} --jwtkeyfile assets/certificates/server.key --username ${{ secrets.SF_USERNAME }}

            - name: Create Scratch org
              run: |
                  node_modules/sfdx-cli/bin/run force:org:create --setdefaultusername --definitionfile config/project-scratch-def.json --wait 10 --durationdays 1
                  node_modules/sfdx-cli/bin/run force:org:display

            - name: Push source to scratch org
              run: node_modules/sfdx-cli/bin/run force:source:push

            - name: Delete Scratch Org
              run: node_modules/sfdx-cli/bin/run force:org:delete --noprompt
